updated workflow and added readme file

diff --git a/.github/workflows/commit_and_fetch.yml b/.github/workflows/commit_and_fetch.yml
--- a/.github/workflows/commit_and_fetch.yml
+++ b/.github/workflows/commit_and_fetch.yml
@@ -5,13 +5,19 @@ on:
     branches:
       - feature/*
     paths-ignore:
-      - 'README.md'
-      - 'Contributing.md'
+      - "README.md"
+      - "Contributing.md"
 
 jobs:
   development:
     name: Fetch and Commit Latest Code
     runs-on: ubuntu-latest
+    env:
+      SOURCE_HOST_URL: ${{ secrets.SOURCE_HOST_URL }}
+      SOURCE_TOKEN: ${{ secrets.SOURCE_TOKEN }}
+      TARGET_HOST_URL: ${{ secrets.TARGET_HOST_URL }}
+      TARGET_TOKEN: ${{ secrets.TARGET_TOKEN }}
+
     steps:
       - name: Check out code
         uses: actions/checkout@v4
@@ -20,21 +26,45 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install pipx
-          
-          LATEST_RELEASE=$(curl -s https://api.github.com/repos/StrawHatEngineer/CICD_2/releases/latest | jq -r .tag_name)
-          pipx install https://github.com/StrawHatEngineer/CICD_2/releases/download/${LATEST_RELEASE}/cicd_aihub-${LATEST_RELEASE}-py3-none-any.whl
+          # Attempt to install from local file first
+          VERSION=$(ls cicd_aihub-*-py3-none-any.whl | sed 's/cicd_aihub-\(.*\)-py3-none-any.whl/\1/' | head -n 1)
+
+          if [ -n "$VERSION" ]; then
+            echo "Found local .whl file: cicd_aihub-${VERSION}-py3-none-any.whl"
+            pipx install cicd_aihub-${VERSION}-py3-none-any.whl
+          else
+            echo "No local .whl file found. Attempting to install from GitHub release."
+            LATEST_RELEASE=$(curl -s https://api.github.com/repos/instabase/aihub-apps-ci-cd-workflows/releases/latest | jq -r .tag_name)
+            VERSION=$(echo $LATEST_RELEASE | sed 's/^v//')
+            
+            if ! pipx install https://github.com/instabase/aihub-apps-ci-cd-workflows/releases/download/${LATEST_RELEASE}/cicd_aihub-${VERSION}-py3-none-any.whl; then
+              echo "Failed to install from GitHub release after failing to find local .whl file. Aborting."
+              exit 1
+            fi
+          fi
+
+      - name: Validate config.json
+        run: |
+          if [ ! -f config.json ]; then
+            echo "Error: config.json file not found"
+            exit 1
+          fi
 
       - name: Fetch Latest App Data
         run: |
           IS_ADVANCED=$(jq -r '.source.is_advanced' config.json)
           SB_NAME=$(jq -r '.source.sb_name' config.json)
           FLOW_PATH=$(jq -r '.source.flow_path' config.json)
+          PROJECT_ID=$(jq -r '.source.project_id' config.json)
           if [ "$IS_ADVANCED" = "true" ] && [ -n "$FLOW_PATH" ] && [ "$FLOW_PATH" != "null" ]; then
             promote-solution --compile_solution --download_solution
           elif [ "$IS_ADVANCED" = "true" ] && [ -n "$SB_NAME" ] && [ "$SB_NAME" != "null" ]; then
             promote-sb-solution --compile_solution --download_solution
-          else
+          elif [ "$IS_ADVANCED" = "false" ] && [ -n "$PROJECT_ID" ] && [ "$PROJECT_ID" != "null" ]; then
             promote-build-solution --compile_solution --download_binary
+          else
+            echo "Error: not a valid config.json"
+            exit 1
           fi
 
       - name: Commit app data to feature branch
@@ -42,7 +72,7 @@ jobs:
           git config --global user.email "no-reply@github.com"
           git config --global user.name "GitHub Actions"
           git config --global --add safe.directory /__w/${{ github.event.repository.name }}/*
-          COMMIT_MESSAGE=$(jq -r '.release_notes' config.json)
+          COMMIT_MESSAGE=$(jq -r '.release_notes // "Automated commit from GitHub Actions"' config.json)
           git add -f .
           git status
           git commit -m "$COMMIT_MESSAGE" --allow-empty
