added release tag on migration

diff --git a/.github/workflows/regression_suite.yml b/.github/workflows/regression_suite.yml
--- a/.github/workflows/regression_suite.yml
+++ b/.github/workflows/regression_suite.yml
@@ -26,7 +26,23 @@ jobs:
       - name: Check out code
         uses: actions/checkout@v4
 
+      - name: Validate config.json
+        id: validate_config
+        run: |
+          if [ ! -f config.json ]; then
+            echo "Error: config.json file not found"
+            exit 1
+          fi
+
+          REGRESSION_COUNT=$(jq -r '.regression | length' config.json)
+          if [ "$REGRESSION_COUNT" -eq 0 ]; then
+            echo "No regression tests found, skipping workflow."
+            echo "skip_workflow=true" >> $GITHUB_ENV
+            exit 0
+          fi
+
       - name: Install dependencies
+        if: env.skip_workflow != 'true'
         run: |
           python -m pip install --upgrade pip
           pip install pipx
@@ -48,26 +64,8 @@ jobs:
             fi
           fi
 
-      - name: Validate config.json
-        run: |
-          if [ ! -f config.json ]; then
-            echo "Error: config.json file not found"
-            exit 1
-          fi
-
-          APP_ID=$(jq -r '.source.app_id' config.json)
-          if [ -z "$APP_ID" ] || [ "$APP_ID" = "null" ]; then
-            echo "Error: app_id is missing or null in config.json"
-            exit 1
-          fi
-
-          REGRESSION=$(jq -r '.regression' config.json)
-          if [ -z "$REGRESSION" ] || [ "$REGRESSION" = "null" ]; then
-            echo "Error: regression is missing or null in config.json"
-            exit 1
-          fi
-
       - name: Run regression tests
+        if: env.skip_workflow != 'true'
         run: |
           IS_ADVANCED=$(jq -r '.source.is_advanced' config.json)
           SB_NAME=$(jq -r '.source.sb_name' config.json)
@@ -82,14 +80,17 @@ jobs:
           fi
       
       - name: Commit regression results to feature branch
+        if: env.skip_workflow != 'true'
         run: |
           git config --global user.email "no-reply@github.com"
           git config --global user.name "GitHub Actions"
           git config --global --add safe.directory /__w/${{ github.event.repository.name }}/*
-          COMMIT_MESSAGE=$(jq -r '.release_notes // "Automated commit from GitHub Actions"' config.json)
-          git add -f .
+          COMMIT_MESSAGE="Regression Results added"
+          git add -f regression_output/
           git status
           git commit -m "$COMMIT_MESSAGE" --allow-empty
+          git fetch origin ${{ github.head_ref }}
+          git rebase origin/${{ github.head_ref }}
           git push origin HEAD:${{ github.head_ref }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
